### ISSUE TITLE
Add channel-energy reference in energy preset

### ISSUE THREAD

**Issue by blebrun** [crp2a/gammaShiny#1]
**Describe the solution you'd like**
It would be nice to add some channel-energy reference by default in the energy preset of the settings tab.

Default values could be :

83 238.63
478 1460.82
856 2614.51

**Comment by nfrerebeau** [comment]
I added these values as placeholder, but not as default values: peak positions can change by more than 20 channels from one spectrum to another. 

E.g.: the peak of 40K corresponds to channel 465 on the BRIQUE spectrum (LaBr CRP2A).
