### ISSUE TITLE
slice_signal does not exist anymore

### ISSUE THREAD

**Issue by blebrun** [crp2a/gammaShiny#6]
**Describe the bug**
Energy calibration tab say `Error : impossible de trouver la fonction slice_signal` while Console return the following warning : `Error in slice_signal: impossible de trouver la fonction "slice_signal" [No stack trace available]`

**To Reproduce**
Load any spectrum in import tab and click on calibration tab.

**Additional context**
In Gamma package, `slice_signal` function does not exist and has been replaced by `signal_slice`.

**Comment by nfrerebeau** [comment]
Update your local installation of the package.
